/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author John
 */
public class Texto extends javax.swing.JFrame {

    /**
     * Creates new form Texto
     */
    public Texto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfcMenu = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaEditar = new javax.swing.JTextArea();
        jmbDocumento = new javax.swing.JMenuBar();
        jmdoc = new javax.swing.JMenu();
        jmiGuardar = new javax.swing.JMenuItem();
        jmiAbrir = new javax.swing.JMenuItem();
        jmComodin = new javax.swing.JMenu();
        jmiMayusculas = new javax.swing.JMenuItem();
        jmiMinisculas = new javax.swing.JMenuItem();
        jmiNegrita = new javax.swing.JMenuItem();
        jmiNormal = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtaEditar.setColumns(20);
        jtaEditar.setRows(5);
        jScrollPane1.setViewportView(jtaEditar);

        jmdoc.setText("Documento");

        jmiGuardar.setText("Guardar");
        jmiGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGuardarActionPerformed(evt);
            }
        });
        jmdoc.add(jmiGuardar);

        jmiAbrir.setText("Abrir");
        jmdoc.add(jmiAbrir);

        jmbDocumento.add(jmdoc);

        jmComodin.setText("Comodin");

        jmiMayusculas.setText("Mayusculas");
        jmComodin.add(jmiMayusculas);

        jmiMinisculas.setText("Minusculas");
        jmComodin.add(jmiMinisculas);

        jmiNegrita.setText("Negrita");
        jmComodin.add(jmiNegrita);

        jmiNormal.setText("Normal");
        jmComodin.add(jmiNormal);

        jmbDocumento.add(jmComodin);

        setJMenuBar(jmbDocumento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Texto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Texto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Texto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Texto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Texto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JFileChooser jfcMenu;
    public javax.swing.JMenu jmComodin;
    public javax.swing.JMenuBar jmbDocumento;
    public javax.swing.JMenu jmdoc;
    public javax.swing.JMenuItem jmiAbrir;
    public javax.swing.JMenuItem jmiGuardar;
    public javax.swing.JMenuItem jmiMayusculas;
    public javax.swing.JMenuItem jmiMinisculas;
    public javax.swing.JMenuItem jmiNegrita;
    public javax.swing.JMenuItem jmiNormal;
    public javax.swing.JTextArea jtaEditar;
    // End of variables declaration//GEN-END:variables
}
